name: Update Formula

on:
  repository_dispatch:
    types: [update_formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout homebrew-cubtera
      uses: actions/checkout@v4

    - name: Update formula
      run: |
        VERSION="${{ github.event.client_payload.version }}"
        VERSION=${VERSION#v}  # Remove 'v' prefix if present
        MAC_INTEL_ZIP_SHA="${{ github.event.client_payload.mac_aarch_zip_sha }}"
        MAC_AARCH_ZIP_SHA="${{ github.event.client_payload.tar_sha }}"
        LINUX_INTEL_ZIP_SHA="${{ github.event.client_payload.linux_intel_zip_sha }}"

        sed -e "s/VERSION/$VERSION/g" \
        -e "s/MAC_INTEL_ZIP_SHA/$MAC_INTEL_ZIP_SHA/g" \
        -e "s/MAC_AARCH_ZIP_SHA/$MAC_AARCH_ZIP_SHA/g" \
        -e "s/LINUX_INTEL_ZIP_SHA/$LINUX_INTEL_ZIP_SHA/g" \
        ./templates/cubtera.tpl.rb > ./Formula/cubtera.rb

        cat ./Formula/cubtera.rb > ./Formula/cubtera.@${VERSION}.rb
  
        # Display the changes
        echo "Updated Formula/cubtera.rb:"
        cat Formula/cubtera.rb
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add Formula/cubtera.rb
        git commit -m "Update cubtera latest version to $VERSION"
        git push